Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # ======================
  # Noyan Control VM
  # ======================
  config.vm.define "Noyan_Control" do |control|
    control.vm.hostname = "noyan-control"
    control.vm.network "private_network", ip: "192.168.56.10"

    control.vm.provider "virtualbox" do |vb|
      vb.name = "Noyan_Control"
      vb.memory = 1536
      vb.cpus = 2
    end
  end

  # ======================
  # Noyan App VM
  # ======================
  config.vm.define "Noyan_App" do |app|
    app.vm.hostname = "noyan-app"
    app.vm.network "private_network", ip: "192.168.56.11"

    app.vm.provider "virtualbox" do |vb|
      vb.name = "Noyan_App"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # ======================
  # Noyan DB VM
  # ======================
  config.vm.define "Noyan_DB" do |db|
    db.vm.hostname = "noyan-db"
    db.vm.network "private_network", ip: "192.168.56.12"

    db.vm.provider "virtualbox" do |vb|
      vb.name = "Noyan_DB"
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
