Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "devops-lab"
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "devops-lab-vm"
    vb.memory = 1048
    vb.cpus   = 1
  end
end